<#
.SYNOPSIS
Build HC_FW_BlackPill through the CMake/Ninja graph generated by VS Code CMake Tools.

.DESCRIPTION
The preferred backend is `Commands`. It asks Ninja for the generated command list and
executes those commands one at a time with per-command timeouts. This preserves the
manual CMake Tools build graph while avoiding the observed Ninja scheduler hang in
this automation environment.
#>

param(
    [ValidateSet('Debug', 'Release')]
    [string]$Preset = 'Debug',

    [string]$Target = 'HC_FW_BlackPill.elf',

    [int]$Jobs = 1,

    [int]$TimeoutSeconds = 120,

    [switch]$DryRun,

    [switch]$VerboseBuild,

    [ValidateSet('Commands', 'Ninja', 'CubeCMake')]
    [string]$Backend = 'Commands',

    [int]$PerCommandTimeoutSeconds = 30
)

$ErrorActionPreference = 'Stop'

# Select the newest installed STM32 VS Code extension matching the given pattern.
# This keeps the wrapper useful after extension upgrades without hard-coding a
# single extension version in the script.
function Get-LatestDirectory {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Pattern
    )

    $dir = Get-ChildItem -Path $Pattern -Directory -ErrorAction SilentlyContinue |
        Sort-Object -Property Name -Descending |
        Select-Object -First 1

    if (-not $dir) {
        throw "Required STM32 VS Code extension directory not found: $Pattern"
    }

    return $dir.FullName
}

# Quote arguments for the .NET ProcessStartInfo.Arguments string. This is used for
# status display and for the diagnostic backends that invoke cube-cmake or Ninja
# directly.
function ConvertTo-CmdArgument {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Argument
    )

    if ($Argument -match '[\s&()^=;!+,`~\[\]{}]') {
        return '"' + ($Argument -replace '"', '\"') + '"'
    }

    return $Argument
}

# Start a bounded diagnostic process with stdout/stderr redirected to log files.
# The normal `Commands` backend does not use this for the real build; it is kept
# for dry runs and for comparing the direct Ninja/cube-cmake behavior.
function Start-LoggedProcess {
    param(
        [Parameter(Mandatory = $true)]
        [string]$FilePath,

        [Parameter(Mandatory = $true)]
        [string[]]$Arguments,

        [Parameter(Mandatory = $true)]
        [string]$WorkingDirectory,

        [Parameter(Mandatory = $true)]
        [string]$StdoutPath,

        [Parameter(Mandatory = $true)]
        [string]$StderrPath
    )

    $startInfo = [System.Diagnostics.ProcessStartInfo]::new()
    $startInfo.FileName = $FilePath
    $startInfo.WorkingDirectory = $WorkingDirectory
    $startInfo.UseShellExecute = $false
    $startInfo.CreateNoWindow = $true
    $startInfo.RedirectStandardOutput = $true
    $startInfo.RedirectStandardError = $true

    $startInfo.Arguments = ($Arguments | ForEach-Object { ConvertTo-CmdArgument $_ }) -join ' '

    $process = [System.Diagnostics.Process]::new()
    $process.StartInfo = $startInfo

    [void]$process.Start()
    $stdoutTask = $process.StandardOutput.ReadToEndAsync()
    $stderrTask = $process.StandardError.ReadToEndAsync()

    return [pscustomobject]@{
        Process = $process
        StdoutTask = $stdoutTask
        StderrTask = $stderrTask
        StdoutPath = $StdoutPath
        StderrPath = $StderrPath
    }
}

# Finish stdout/stderr collection after a direct process exits or is stopped.
function Complete-LoggedProcess {
    param(
        [Parameter(Mandatory = $true)]
        [pscustomobject]$Handle
    )

    try {
        $stdout = $Handle.StdoutTask.GetAwaiter().GetResult()
        [System.IO.File]::WriteAllText($Handle.StdoutPath, $stdout)
    } catch {
        [System.IO.File]::WriteAllText($Handle.StdoutPath, "stdout capture failed: $_")
    }

    try {
        $stderr = $Handle.StderrTask.GetAwaiter().GetResult()
        [System.IO.File]::WriteAllText($Handle.StderrPath, $stderr)
    } catch {
        [System.IO.File]::WriteAllText($Handle.StderrPath, "stderr capture failed: $_")
    }
}

# Kill only build-tool processes that started after this wrapper launched an action.
# This avoids leaving a hung compiler/Ninja/cube-cmake child behind while reducing
# the risk of touching unrelated user processes.
function Stop-BuildProcessesStartedAfter {
    param(
        [Parameter(Mandatory = $true)]
        [datetime]$StartTime
    )

    $names = 'cmd', 'cube-cmake', 'cmake', 'ninja', 'arm-none-eabi-gcc', 'arm-none-eabi-g++'
    Get-Process -ErrorAction SilentlyContinue |
        Where-Object {
            $names -contains $_.ProcessName -and
            $_.StartTime -ge $StartTime
        } |
        Stop-Process -Force -ErrorAction SilentlyContinue
}

# Warn when the checked-in VS Code settings no longer point at the same STM32
# extension tools this wrapper discovered. The wrapper can still run, but a warning
# means the automated path and the manual CMake Tools path may have drifted.
function Test-VSCodeCMakeSettings {
    param(
        [Parameter(Mandatory = $true)]
        [string]$RepoRoot,

        [Parameter(Mandatory = $true)]
        [string]$CubeCmakePath,

        [Parameter(Mandatory = $true)]
        [string]$CoreBinaryPath
    )

    $settingsPath = Join-Path $RepoRoot '.vscode\settings.json'
    if (-not (Test-Path $settingsPath)) {
        Write-Warning ".vscode\settings.json not found; cannot compare against the manual VS Code CMake Tools environment."
        return
    }

    try {
        $settings = Get-Content -Raw -Path $settingsPath | ConvertFrom-Json
    } catch {
        Write-Warning "Unable to parse .vscode\settings.json; cannot compare against the manual VS Code CMake Tools environment. $_"
        return
    }

    if ($settings.'cmake.cmakePath' -ne 'cube-cmake') {
        Write-Warning "VS Code setting cmake.cmakePath is not 'cube-cmake'. Manual and wrapper builds may use different CMake frontends."
    }

    if ($settings.'cmake.preferredGenerators' -notcontains 'Ninja') {
        Write-Warning "VS Code setting cmake.preferredGenerators does not include Ninja. Manual and wrapper builds may use different generators."
    }

    $configurePath = $settings.'cmake.configureEnvironment'.PATH
    $buildPath = $settings.'cmake.buildEnvironment'.PATH
    foreach ($requiredPath in @($CubeCmakePath, $CoreBinaryPath)) {
        if ($configurePath -and $configurePath -notlike "*$requiredPath*") {
            Write-Warning "VS Code configure PATH does not contain discovered STM32 tool path: $requiredPath"
        }
        if ($buildPath -and $buildPath -notlike "*$requiredPath*") {
            Write-Warning "VS Code build PATH does not contain discovered STM32 tool path: $requiredPath"
        }
    }
}

# Reliable backend: extract the exact commands from the generated Ninja graph and
# run them serially. This deliberately bypasses Ninja scheduling/incrementality,
# but it still uses the CMake Tools-generated build graph and target commands.
function Invoke-CommandListBuild {
    param(
        [Parameter(Mandatory = $true)]
        [string]$NinjaPath,

        [Parameter(Mandatory = $true)]
        [string]$BuildDirectory,

        [Parameter(Mandatory = $true)]
        [string]$TargetName,

        [Parameter(Mandatory = $true)]
        [string]$StdoutPath,

        [Parameter(Mandatory = $true)]
        [string]$StderrPath,

        [Parameter(Mandatory = $true)]
        [int]$PerCommandTimeout
    )

    $commands = @(& $NinjaPath -C $BuildDirectory -t commands $TargetName)
    if ($LASTEXITCODE -ne 0) {
        "ninja -t commands failed with exit code $LASTEXITCODE" | Set-Content -Path $StderrPath
        return $LASTEXITCODE
    }

    "command count: $($commands.Count)" | Set-Content -Path $StdoutPath
    "" | Set-Content -Path $StderrPath

    $index = 0
    foreach ($command in $commands) {
        $index++
        "[$index/$($commands.Count)] $command" | Add-Content -Path $StdoutPath

        # Commands emitted by Ninja are Windows shell command lines, so execute
        # them through cmd.exe while still applying a timeout to each command.
        $startTime = Get-Date
        $startInfo = [System.Diagnostics.ProcessStartInfo]::new()
        $startInfo.FileName = $env:ComSpec
        $startInfo.Arguments = "/d /s /c $command"
        $startInfo.WorkingDirectory = $BuildDirectory
        $startInfo.UseShellExecute = $false
        $startInfo.CreateNoWindow = $true
        $startInfo.RedirectStandardOutput = $true
        $startInfo.RedirectStandardError = $true

        $process = [System.Diagnostics.Process]::new()
        $process.StartInfo = $startInfo
        [void]$process.Start()
        $stdoutTask = $process.StandardOutput.ReadToEndAsync()
        $stderrTask = $process.StandardError.ReadToEndAsync()

        $completed = $process.WaitForExit($PerCommandTimeout * 1000)
        if (-not $completed) {
            Stop-Process -Id $process.Id -Force -ErrorAction SilentlyContinue
            Stop-BuildProcessesStartedAfter -StartTime $startTime
            try { $stdoutTask.GetAwaiter().GetResult() | Add-Content -Path $StdoutPath } catch {}
            try { $stderrTask.GetAwaiter().GetResult() | Add-Content -Path $StderrPath } catch {}
            "timeout after ${PerCommandTimeout}s: $command" | Add-Content -Path $StderrPath
            return 124
        }

        $process.Refresh()
        $stdoutTask.GetAwaiter().GetResult() | Add-Content -Path $StdoutPath
        $stderrTask.GetAwaiter().GetResult() | Add-Content -Path $StderrPath

        if ($process.ExitCode -ne 0) {
            "command failed with exit code $($process.ExitCode): $command" | Add-Content -Path $StderrPath
            return $process.ExitCode
        }
    }

    return 0
}

$repoRoot = Resolve-Path (Join-Path $PSScriptRoot '..')
$extensionRoot = Join-Path $env:USERPROFILE '.vscode\extensions'
$buildCmakeExt = Get-LatestDirectory (Join-Path $extensionRoot 'stmicroelectronics.stm32cube-ide-build-cmake-*-win32-x64')
$coreExt = Get-LatestDirectory (Join-Path $extensionRoot 'stmicroelectronics.stm32cube-ide-core-*-win32-x64')

$cubeCmakePath = Join-Path $buildCmakeExt 'resources\cube-cmake\win32\x86_64'
$stm32CoreBinaryPath = Join-Path $coreExt 'resources\binaries\win32\x86_64'

if (-not (Test-Path (Join-Path $cubeCmakePath 'cube-cmake.exe'))) {
    throw "cube-cmake.exe not found in $cubeCmakePath"
}

# Model the STM32 extension environment before resolving cube-cmake or Ninja.
$env:PATH = "$cubeCmakePath;$stm32CoreBinaryPath;$env:PATH"
Test-VSCodeCMakeSettings -RepoRoot $repoRoot -CubeCmakePath $cubeCmakePath -CoreBinaryPath $stm32CoreBinaryPath

$cubeCmake = (Get-Command cube-cmake -ErrorAction Stop).Source

# Prefer the STM32-managed Ninja bundle because that is what the extension places
# in the generated build environment. Fall back to PATH only if the bundle is absent.
$ninja = Join-Path $env:USERPROFILE 'AppData\Local\stm32cube\bundles\ninja\1.13.2+st.1\bin\ninja.exe'
if (-not (Test-Path $ninja)) {
    $ninja = (Get-Command ninja -ErrorAction Stop).Source
}
$buildDir = Join-Path $repoRoot "build\$Preset"
New-Item -ItemType Directory -Force -Path $buildDir | Out-Null

$stamp = Get-Date -Format 'yyyyMMdd_HHmmss'
$mode = if ($DryRun) { 'dry_run' } else { 'build' }
$stdoutLog = Join-Path $buildDir "cube_cmake_${mode}_${stamp}.out.log"
$stderrLog = Join-Path $buildDir "cube_cmake_${mode}_${stamp}.err.log"

$tool = $cubeCmake
$arguments = @()

# Backend selection:
# - Commands: reliable default; generated Ninja command list with per-command timeout.
# - Ninja: diagnostic path for the normal Ninja scheduler.
# - CubeCMake: diagnostic path for the VS Code/ST command layer.
if ($Backend -eq 'CubeCMake') {
    $arguments = @(
        '--build', '--preset', $Preset,
        '--target', $Target,
        '--parallel', $Jobs
    )

    if ($DryRun -or $VerboseBuild) {
        $arguments += '--'
        if ($DryRun) {
            $arguments += '-n'
        }
        $arguments += '-v'
    }
} elseif ($Backend -eq 'Ninja') {
    $tool = $ninja
    $arguments = @(
        '-C', $buildDir,
        '-j', $Jobs
    )

    if ($DryRun) {
        $arguments += '-n'
    }

    if ($DryRun -or $VerboseBuild) {
        $arguments += '-v'
    }

    $arguments += $Target
} else {
    $tool = $ninja
    $arguments = @('-C', $buildDir, '-t', 'commands', $Target)
}

$commandLine = (ConvertTo-CmdArgument $tool) + ' ' + (($arguments | ForEach-Object { ConvertTo-CmdArgument $_ }) -join ' ')

Write-Output "cube-cmake: $cubeCmake"
Write-Output "ninja: $ninja"
Write-Output "backend: $Backend"
Write-Output "preset: $Preset"
Write-Output "target: $Target"
Write-Output "jobs: $Jobs"
Write-Output "dry run: $([bool]$DryRun)"
Write-Output "command: $commandLine"
Write-Output "stdout: $stdoutLog"
Write-Output "stderr: $stderrLog"

if ($Backend -eq 'Commands' -and -not $DryRun) {
    $exitCode = Invoke-CommandListBuild `
        -NinjaPath $ninja `
        -BuildDirectory $buildDir `
        -TargetName $Target `
        -StdoutPath $stdoutLog `
        -StderrPath $stderrLog `
        -PerCommandTimeout $PerCommandTimeoutSeconds

    Write-Output "exit code: $exitCode"
    Write-Output '--- stdout tail ---'
    Get-Content -Path $stdoutLog -Tail 80 -ErrorAction SilentlyContinue
    Write-Output '--- stderr tail ---'
    Get-Content -Path $stderrLog -Tail 80 -ErrorAction SilentlyContinue
    exit $exitCode
}

$startTime = Get-Date
$handle = Start-LoggedProcess -FilePath $tool -Arguments $arguments -WorkingDirectory $repoRoot -StdoutPath $stdoutLog -StderrPath $stderrLog
$process = $handle.Process

$completed = $process.WaitForExit($TimeoutSeconds * 1000)

if (-not $completed) {
    Stop-Process -Id $process.Id -Force -ErrorAction SilentlyContinue
    Stop-BuildProcessesStartedAfter -StartTime $startTime
    Complete-LoggedProcess -Handle $handle
    Write-Output "timeout: build process exceeded ${TimeoutSeconds}s and was stopped"
    exit 124
}

$process.WaitForExit()
$process.Refresh()
$exitCode = $process.ExitCode
Complete-LoggedProcess -Handle $handle
Write-Output "exit code: $exitCode"

Write-Output '--- stdout tail ---'
Get-Content -Path $stdoutLog -Tail 80 -ErrorAction SilentlyContinue

Write-Output '--- stderr tail ---'
Get-Content -Path $stderrLog -Tail 80 -ErrorAction SilentlyContinue

exit $exitCode
